config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  
  devise_for :users
  
  get 'about', to: 'pages#about'
  
  
  resources :users
  
  get 'dashboard', to: 'users#dashboard'
  
  resources :goals do
    resources :activities
  end
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :goals
  has_many :activities
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  helper_method :sort_column, :sort_direction
  
  def show
    @goals = current_user.goals
    @activities = current_user.activities.all.reverse
  end
  
  def dashboard
    @goals = current_user.goals
    @activities = current_user.activities.all.reverse
    @table_today_goals = @goals.order("#{sort_column} #{sort_direction}")
    @table_total_goals = @goals.order("#{sort_column} #{sort_direction}")
  end
  
  private 
  
  def sortable_columns
  ["xp", "xp_today", "total_goal_xp"]
  end

  def sort_column
    sortable_columns.include?(params[:column]) ? params[:column] : "name"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def sort_link(column, title = nil)
    title ||= column.titleize
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    icon = sort_direction == "asc" ? "fa fa-caret-up" : "fa fa-caret-down"
    icon = column == sort_column ? icon : ""
    link_to "#{title} <span class='#{icon}'></span>".html_safe, {column: column, direction: direction}
  end
end

app/views/users/dashboard.html.erb
<div class="dashboard-container">
  <h1 class="text-center">Dashboard</h1>
  <hr>
  <div class="row">
    <div class="col-md-2">
      <h4 class="text-center">Scoreboard</h4>
      <hr>
      <div class="well dashboard-score-well">
        <p>Longest +ve streak: N/A</p>
        <p>Longest -ve streak: N/A</p>
        <p>Highest Daily Xp: N/A</p>
        <p>Highest Goal Xp</p>
      </div>
    </div>
    <div class="col-md-8">
      <div class="row">
        <h4 class="text-center">Daily Breakdown</h4>
        <hr>
        <% if @goals.count > 0 %>
        <div class="col-md-4">
          <% if current_user.user_xp_today > 0 %>
            <div class="daily-piechart">
              <%= pie_chart  @goals.group(:name).sum(:xp_today), library: { chartArea: {left: 20, top: -500 , width: "300%", height: "300%"} } %>
            </div>
          <% else %>
            <p class="text-center no-xp-message">You haven't earned any XP today...</p>
          <% end %>
        </div>
        <div class="col-md-8">
          <table class="table table-striped table-hover">
            <thead>
              <th><stong>Goal</stong></th>
              <th><stong><%= sort_link "xp" %></stong></th>
              <th><stong><%= sort_link "xp_today" %></stong></th>
              <th><stong>Actions</stong></th>
            </thead>
            <tbody>
              <% @table_today_goals.each do |goal| %>
              <tr>
                <td><%= link_to goal.name, goal_path(goal), class: "goal-title" %></td>
                <td><%= goal.xp %></td>
                <td><%= goal.xp_today %></td>
                <td>
                  <%= link_to edit_goal_path(goal), class: "btn btn-xs btn-default" do %>
                    <i class="fa fa-edit"></i>
                  <% end %>
                  <%= link_to goal_path(goal), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-xs btn-danger" do %>
                    <i class="fa fa-trash-o"></i>
                  <% end %>
                </td>
              </tr>
              <% end %>
            </tbody>
          </table>
        </div>
        <% else %>
          <p class="text-center">You have no goals! Click <%= link_to "here", new_goal_path %> to create your first one.</p>
          </br>
          </br>        
        <% end %>
      </div>
      <div class="row">
        <h4 class="text-center">Overall Breakdown</h4>
        <hr>
        <% if @goals.count > 0 %>
        <div class="col-md-4">
          <% if current_user.total_user_xp > 0 %>
          <div class="overall-piechart">
            <%= pie_chart  @goals.group(:name).sum(:total_goal_xp), library: { chartArea: {left: 20, top: -200, width: "100%", height: "100%"} } %>
          </div>
          <% else %>
            <p class="text-center no-xp-message">You haven't earned any XP yet...</p>
          <% end %>
        </div>
        <div class="col-md-8">
          <table class="table table-striped table-hover">
            <thead>
              <th><stong>Goal</stong></th>
              <th><stong><%= sort_link "xp" %></stong></th>
              <th><stong><%= sort_link "total_goal_xp" %></stong></th>
              <th><stong>Actions</stong></th>
            </thead>
            <tbody>
              <% @table_total_goals.each do |goal| %>
              <tr>
                <td><%= link_to goal.name, goal_path(goal), class: "goal-title" %></td>
                <td><%= goal.xp %></td>
                <td><%= goal.total_goal_xp %></td>
                <td>
                  <%= link_to edit_goal_path(goal), class: "btn btn-xs btn-default" do %>
                    <i class="fa fa-edit"></i>
                  <% end %>
                  <%= link_to goal_path(goal), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-xs btn-danger" do %>
                    <i class="fa fa-trash-o"></i>
                  <% end %>
                </td>
              </tr>
              <% end %>
            </tbody>
          </table>
        </div>
        <% else %>
          <p class="text-center">You have no goals! Click <%= link_to "here", new_goal_path %> to create your first one.</p>
        <% end %>
      </div>
    </div>
    <div class="col-md-2">
      <h4 class="text-center">Recent Activity</h4>
      <hr>
      <% if @activities.count > 0 %>
        <% @activities.each do |activity| %>
          <div class="well well-activity <%= cycle(" ", "bg-white")%>">
            <p class="text-center">You completed <%= pluralize(activity.quantity, "set") %> of <%= link_to (activity.goal.name).downcase, goal_path(activity.goal) %></p>
            <div class="text-center">
              <small><%= time_ago_in_words(activity.created_at) %> ago</small>
            </div>
            <div class="activity-actions">
              <%= link_to goal_activity_path(goal_id: activity.goal_id, id: activity.id), method: :delete, data: {confirm: "Are you sure you want to delete this activity?"}, class: "btn btn-xs btn-default" do %>
                <i class="fa fa-trash-o"></i>
              <% end %>
            </div>
          </div>
        <% end %>
      <% else %>
        <p class="text-center">Get a move on!</p>
        <p class="text-center">You have no recorded activities, yet...</p>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<% @activities.each do |activity| %>
  <div class="well well-activity <%= cycle(" ", "bg-white")%>">
    <p class="text-center">You completed <%= pluralize(activity.quantity, "set") %> of <%= link_to activity.goal.name, goal_path(activity.goal) %> </p>
    <div class="text-center">
      <small><%= time_ago_in_words(activity.created_at) %> ago </small>
    </div>
  </div>
<% end %>