config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  
  devise_for :users
  
  get 'about', to: 'pages#about'
  
  
  resources :users
  
  get 'dashboard', to: 'users#dashboard'
  
  resources :goals do
    resources :activities
  end
  
end

app/models/goal.rb
class Goal < ActiveRecord::Base
  belongs_to :user
  has_many :goal_activities, dependent: :destroy
  has_many :activities, through: :goal_activities
  
  after_destroy :reset_total_user_xp
  after_commit :reset_goal_xp, on: :update
  after_find :set_daily_xp
  
  private
  
  def reset_total_user_xp
    user = self.user
    user.update_attribute(:total_user_xp, user.goals.sum(:total_goal_xp))
  end
  
  def reset_goal_xp
    self.update_attribute(:total_goal_xp, self.goal_activities.sum(:total_xp))
  end 
  
  def set_daily_xp
    todays_goals = self.goal_activities.where("created_at >= ?", Time.zone.now.beginning_of_day)
    self.update_column(:xp_today, todays_goals.sum(:total_xp))
  end

end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_action :set_goal, only: [:edit, :update, :show, :destroy]
  before_action :authenticate_user!
  before_action :require_same_user, only: [:edit, :update, :destroy]
  
  def new
    @goal = Goal.new
  end
  
  def create
    @goal = Goal.new(goal_params)
    @goal.user = current_user
    if @goal.save
      flash[:success] = "Your goal has been created!"
      redirect_to goals_path
    else
      flash[:danger] = Goal.errors.full_message.join(" ,")
      render 'new'
    end
  end
  
  def edit
  end
  
  def update
    if @goal.update(goal_params)
      flash[:success] = "Goal was successfully updated"
      redirect_to goal_path(@goal)
    else
      flash[:danger] = Goal.errors.full_message.join(" ,")
      render 'edit'
    end
  end
  
  def show
    @total_goal_xp = @goal.total_goal_xp
    @activities = @goal.goal_activities
    @goal_activities = @goal.activities.all.reverse
  end
  
  def index
    @user = current_user
    @user_goals = @user.goals
  end
  
  def destroy
    @goal.destroy
    flash[:danger] = "Goal was successfully deleted"
    redirect_to goals_path
  end
  
  def dashboard
    @goals = current_user.goals
    @goals_today = Goal.completed_goal_today
  end

  private
  def goal_params
    params.require(:goal).permit(:name, :xp, :total_goal_xp, :description)
  end
  
  def set_goal
    @goal = Goal.find(params[:id])
  end
  
  def require_same_user
    if @goal.user != current_user
      flash[:danger] = "You can only view your own goals"
      redirect_to root_path
    end
  end
end

app/helpers/goals_helper.rb
module GoalsHelper
  def goal_level
    if @goal.total_goal_xp >= (@goal.xp*200)
      "Completed it m8".html_safe
    elsif  @goal.total_goal_xp >= (@goal.xp*100)
      "5 (#{(@goal.xp*200-@goal.total_goal_xp)}xp to Level 6)".html_safe
    elsif @goal.total_goal_xp >= (@goal.xp*50)
      "4 (#{(@goal.xp*100-@goal.total_goal_xp)}xp to Level 5)".html_safe
    elsif @goal.total_goal_xp >= (@goal.xp*25)
      "3 (#{(@goal.xp*50-@goal.total_goal_xp)}xp to Level 4)".html_safe
    elsif @goal.total_goal_xp >= (@goal.xp*5)
      "2 (#{(@goal.xp*25-@goal.total_goal_xp)}xp to Level 3)".html_safe
    else
      "1 (#{(@goal.xp*5-@goal.total_goal_xp)}xp to Level 2)".html_safe
    end
  end
  
  def goal_level_set_difference
    if @goal.total_goal_xp >= (@goal.xp*200)
      " - Completed it m8".html_safe
    elsif  @goal.total_goal_xp >= (@goal.xp*100)
      "Only #{pluralize(((@goal.xp*200-@goal.total_goal_xp)/@goal.xp), "set")} to level up!".html_safe
    elsif @goal.total_goal_xp >= (@goal.xp*50)
      "Only #{pluralize(((@goal.xp*100-@goal.total_goal_xp)/@goal.xp), "set")} to level up!".html_safe
    elsif @goal.total_goal_xp >= (@goal.xp*25)
      "Only #{pluralize(((@goal.xp*50-@goal.total_goal_xp)/@goal.xp), "set")} to level up!".html_safe
    elsif @goal.total_goal_xp >= (@goal.xp*5)
      "Only #{pluralize(((@goal.xp*25-@goal.total_goal_xp)/@goal.xp), "set")} to level up!".html_safe
    else
      "Only #{pluralize(((@goal.xp*5-@goal.total_goal_xp)/@goal.xp), "set")} to level up!".html_safe
    end
  end
  
  def goal_chart_range
    if @goal.total_goal_xp >= (@goal.xp*200)
      "#{@goal.xp*500}".html_safe
    elsif  @goal.total_goal_xp >= (@goal.xp*100)
      "#{@goal.xp*200}".html_safe
    elsif @goal.total_goal_xp >= (@goal.xp*50)
      "#{@goal.xp*100}".html_safe
    elsif @goal.total_goal_xp >= (@goal.xp*25)
      "#{@goal.xp*50}".html_safe
    elsif @goal.total_goal_xp >= (@goal.xp*5)
      "#{@goal.xp*25}".html_safe
    else
      "#{@goal.xp*5}".html_safe
    end
  end
end

app/views/goals/_form.html.erb
<%= form_for(@goal, :html => {role: "form"}) do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class:"form-control", placeholder: "Enter goal name..." %>
  </div>
  
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, rows: 10, class:"form-control", placeholder: "Write a quick motivational message to keep you inspired..." %>
  </div>
  
  <div class="form-group">
    <%= f.label :xp %>
    <%= f.number_field :xp, min: 1, max: 5000, class:"form-control", placeholder: "Enter XP value..." %>
  </div>
  
  <div class="form-group">
    <%= f.submit class:"btn btn-success btn-md" %>
  </div>
  
<% end %>

<div class="col-md-12 text-center">  
  [ <%= link_to 'Return to goals', goals_path %> ]
</div>
</br>

app/views/goals/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <h1 class="text-center">Edit Goal</h1>
      </br>
      <div class="well">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/goals/index.html.erb
<div class="container">
  <div> <!--Goal Sheet-->
    <h1 class="text-center">Goal Sheet</h1>
    <hr>
    </br>
    <div class="row">
      <div class="col-md-8 col-md-offset-2">
        <% if current_user.goals.count > 0 %>
          <table class="table table-striped">
            <thead>
              <th><stong>Goal</stong></th>
              <th><stong>XP</stong></th>
              <th><stong>Total XP</stong></th>
              <th><stong>XP Today</stong></th>
              <th><stong>Actions</stong></th>
            </thead>
            <tbody>
              <% @user_goals.each do |goal| %>
              <tr>
                <td><%= link_to goal.name, goal_path(goal), class: "goal-title" %></td>
                <td><%= goal.xp %></td>
                <td><%= goal.total_goal_xp %></td>
                <td><%= goal.xp_today %></td>
                <td>
                  <%= link_to edit_goal_path(goal), class: "btn btn-xs btn-default" do %>
                    <i class="fa fa-edit"></i>
                  <% end %>
                  <%= link_to goal_path(goal), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-xs btn-danger" do %>
                    <i class="fa fa-trash-o"></i>
                  <% end %>
                </td>
              </tr>
              <% end %>
            </tbody>
          </table>
          <%= link_to "Create new goal", new_goal_path, class:"btn btn-primary btn-md" %>
        <% else %>
          <h4 class="text-center">You have no goals yet!</h4>
          </br>
          <div class="text-center">
            <%= link_to "Create your first goal", new_goal_path, class:"btn btn-primary btn-lg" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/goals/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <h1 class="text-center">Create Goal</h1>
      </br>
      <div class="well">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/goals/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      </br>
      <div class="well score-well">
        <h3 class="text-center">Scoreboard</h3>
        <hr>
        <p>XP per set: <%= @goal.xp %>xp</p>
        <p>Level: <%= goal_level %></p>
        <p>Total XP: <%= @goal.total_goal_xp %>xp</p>
        <p>Total Count: <%= @goal.activities.sum(:quantity) %></p>
        <p>XP Today: <%= @goal.xp_today %></p>
        <p>Highest Daily Score: N/A</p>
      </div>
      <div class="text-center back-goals-button">
        <%= link_to "< Back to Goals", goals_path, class: "btn btn-md btn-default" %>
      </div>
    </div>
    <div class="col-md-6 goal-menu">
      <div class="navbarnavbar-default navbar-static-top" role="navigation">
        <div class="collapse navbar-collapse dropdown" id="main-nav-collapse">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            <h1 class="text-center"><%= @goal.name.titleize %><span class="fa fa-caret-down" style="margin-left: 20px; font-size: 24px;"></span></h1>
            <ul class="dropdown-menu dropdown-menu-right">
              <li><%= link_to "Log Activity", new_goal_activity_path(@goal) %></li>
              <li><%= link_to "Edit Goal", edit_goal_path(@goal) %></li>
              <li><%= link_to "Delete Goal", goal_path, method: :delete, data: {confirm: "Are you sure you want to delete the goal?"} %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "New Goal", new_goal_path %></li>
            </ul>
          </a>
        </div>
      </div>
      <hr>
      <h4 class="text-center">"<%= @goal.description %>" - <%= @goal.user.email %></h4>
      <p class="text-center"><%= goal_level_set_difference %></p>
      <hr>
      <h4>Weekly Progress</h4>
      </br>
      <div class="well chart-well"><%= line_chart @activities.group_by_day(:created_at, last: 7).sum(:total_xp), library: { hAxis: { format: 'dd/MM' }, vAxis: { viewWindow: {min: 0, max: (@goal.xp*25) } }, pointSize: 4 } %></div>
    </div>
    <div class="col-md-3">
      <a data-toggle="collapse" data-parent="#accordian" href="#collapseOne">
        <h4 class="log-activity">Log Activity<span class="fa fa-caret-down" style="margin-left: 5px"></span></h4>
      </a>
      <div id="collapseOne" class="panel-collapse collapse">
        <div class="panel-body">
          <%= render 'activities/form' %>
        </div>
      </div>
      <hr class="hr-activity-bar">
      <div class="recent-activity">
        <h4 class="recent-activity-header">Recent Activity</h4>
        <% if @goal_activities.count > 0 %>
          <% @goal_activities.each do |activity| %>
            <div class="well well-activity <%= cycle(" ", "bg-white")%>">
              <p class="text-center">You completed <%= pluralize(activity.quantity, "set") %> of <%= (activity.goal.name).downcase %> - <strong><%= activity.quantity*activity.goal.xp %>xp</strong></p>
              <div class="text-center">
                <small><%= time_ago_in_words(activity.created_at) %> ago </small>
              </div>
              <div class="activity-actions">
                <%= link_to goal_activity_path(goal_id: activity.goal_id, id: activity.id), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-xs btn-default" do %>
                  <i class="fa fa-trash-o"></i>
                <% end %>
              </div>
            </div>
          <% end %>
        <% else %>
          <br>
          <div class="text-center">
            <p>You have no activities recorded yet! Log your first one by click on the button blelow</p>
            <br>
            <%= link_to "Log Activity", new_goal_activity_path(@goal), class:"btn btn-default btn-md" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>