config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  
  devise_for :users
  
  get 'about', to: 'pages#about'
  
  
  resources :users
  
  get 'dashboard', to: 'users#dashboard'
  
  resources :goals do
    resources :activities
  end
  
end

app/models/activity.rb
class Activity < ActiveRecord::Base
  has_many :goal_activities, dependent: :destroy
  belongs_to :goal
  belongs_to :user
  
  after_create :set_total_xp
  after_destroy :reset_total_xp
  
  private
  
  def set_total_xp
    goal_activity = self.goal_activities.where(goal_id: goal_id).first_or_initialize
    goal_activity.update_attribute(:total_xp, (quantity*goal.xp))
    goal = Goal.find_by_id(goal_id)
    todays_goals = goal.goal_activities.where("created_at >= ?", Time.zone.now.beginning_of_day)
    user = goal.user
    goal.update_attribute(:total_goal_xp, goal.goal_activities.sum(:total_xp))
    goal.update_attribute(:xp_today, todays_goals.sum(:total_xp))
    user.update_attribute(:user_xp_today, user.goals.sum(:xp_today))
    user.update_attribute(:total_user_xp, user.goals.sum(:total_goal_xp))
  end
  
  def reset_total_xp
    goal = Goal.find_by_id(goal_id)
    todays_goals = goal.goal_activities.where("created_at >= ?", Time.zone.now.beginning_of_day)
    user = goal.user
    goal.update_attribute(:total_goal_xp, goal.goal_activities.sum(:total_xp))
    goal.update_attribute(:xp_today, todays_goals.sum(:total_xp))
    user.update_attribute(:user_xp_today, user.goals.sum(:xp_today))
    user.update_attribute(:total_user_xp, user.goals.sum(:total_goal_xp))
  end
  

  
  # def set_total_xp
  #   goal_activity = self.goal_activities.where(goal_id: goal_id).first_or_initialize
  #   goal_activity.update_attribute(:total_xp, (quantity*goal.xp))
  #   goal = Goal.find_by_id(goal_id)
  #   xp = goal_activity.total_xp
  #   goal.update_attribute(:total_goal_xp, (goal.total_goal_xp + xp))
  #   user = goal.user
  #   user.update_attribute(:total_user_xp, (user.total_user_xp + xp))
  # end
end

  # def self.set_xp_today
  #   goal_activities = Goal.goal_activities.where("created_at >= ?", Time.zone.now.beginning_of_day).sum(:total_xp)
  #   self.update_attribute(:xp_today, goal.goal_activities.sum(:total_xp))
  # end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :set_activity, only: [:show, :edit, :update, :destroy]

  # GET /activities
  # GET /activities.json
  def index
    @activities = Activity.all
  end

  # GET /activities/1
  # GET /activities/1.json
  def show
  end

  # GET /activities/new
  def new
    @activity = Activity.new
    @goal = Goal.find(params[:goal_id])
    @user = current_user
  end

  # GET /activities/1/edit
  def edit
    @goal = Goal.find(params[:goal_id])
    @user = current_user
  end

  # POST /activities
  # POST /activities.json
  def create
    @activity = Activity.new(activity_params)
    @activity.goal = Goal.find(params[:goal_id])
    @activity.user = current_user
    if @activity.save
      flash[:success] = "You just gained #{@activity.quantity*@activity.goal.xp}xp!"
      redirect_to goal_path(@activity.goal)
    else
      redirect_to new_goal_activity_path(@activity.goal)
      flash[:danger] = "There was a problem logging your activity"
    end
  end

  # PATCH/PUT /activities/1
  # PATCH/PUT /activities/1.json
  def update
    @goal = Goal.find(params[:goal_id])
    @activity = Activity.find(params[:id])
    @user = current_user
    if @activity.update(activity_params)
      flash[:success] = "Activity was successfully updated"
      redirect_to goal_path(@activity.goal)
    else
      flash[:danger] = "There was a problem updating your activity"
      render 'edit'
    end
  end

  # DELETE /activities/1
  # DELETE /activities/1.json
  def destroy
    @goal = Goal.find(params[:goal_id])
    @activity.destroy
      flash[:danger] = "Activity was successfully deleted"
      redirect_to goal_path(@activity.goal)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activity
      @activity = Activity.find(params[:id])
    end
    
    def set_goal
      @goal = Goal.find(params[:goal_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def activity_params
      params.require(:activity).permit(:quantity, :goal_id)
    end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/views/activities/_form.html.erb
<%= form_for Activity.new, url: goal_activities_path(@goal) do |f| %>
  <div class="field form-group">
    <%= f.label :quantity %>
    <%= f.number_field :quantity, class:"form-control" %>
  </div>
  
  <div class="actions form-group">
    <%= f.submit "Log Activity", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/activities/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <h1 class="text-center">Edit Activity for <%= @goal.name %></h1>
      <div class="well">
        <%= form_for @activity, :url => { :action => "update" } do |form| %>
        <%= render partial: 'form', locals: { f: form } %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/activities/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <h1 class="text-center">Log Activity for "<%= @goal.name %>"</h1>
      </br>
      <div class="well">
        <%= form_for(@activity, url: goal_activities_path(@goal), :html => {role: "form"}) do |f| %>
          <div class="field form-group">
            <%= f.label :quantity %>
            <%= f.number_field :quantity, class:"form-control" %>
          </div>
          
          <div class="actions form-group">
            <%= f.submit "Log Activity", class: 'btn btn-primary' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>