config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  
  devise_for :users
  
  get 'about', to: 'pages#about'
  
  
  resources :users
  
  get 'dashboard', to: 'users#dashboard'
  
  resources :goals do
    resources :activities
  end
  
end

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default navbar-static-top" role="navigation">
  <div class='container'>
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main-nav-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to root_path, class: "navbar-brand" do %>
        <i class="fa fa-trophy"></i>
        Goal Tracka
      <% end %>
    </div>
    <div class="collapse navbar-collapse" id="main-nav-collapse">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to "Dashboard", dashboard_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Goals<span class="caret"></span></a>
            <ul class="dropdown-menu">
              <% current_user.goals.each do |goal| %>
                <li><%= link_to goal.name, goal_path(goal) %></li>
              <% end %>
              <% if current_user.goals.count > 0 %>
                <li role="separator" class="divider"></li>
              <% end %>
              <li><%= link_to "New  Goal", new_goal_path %></li>
              <li><%= link_to "All Goals", goals_path %></li>
            </ul>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Profile<span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "View Profile", user_path(current_user) %></li>
              <li><%= link_to "Edit Profile", edit_user_registration_path(current_user) %></li>
            </ul>
          </li>
          <%= link_to "Log Out", destroy_user_session_path, method: :delete, class:"btn btn-default navbar-btn" %>
        <% else %>
          <%= link_to "Log In", new_user_session_path, class:"btn btn-default navbar-btn" %>
          <%= link_to "Sign Up", new_user_registration_path, class:"btn btn-default navbar-btn" %>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Goaltracka</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    '//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag '//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js', 'data-turbolinks-track' => true %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "https://www.google.com/jsapi" %>
  </head>
  
  <%= render 'layouts/navigation' %>
  
  <body>
    <div class="flash-container text-center col-xs-6 col-xs-offset-3">
      <% flash.each do |type, msg| %>
        <%= content_tag :div, msg, class: "alert alert-#{type}"  %>
      <% end %>
    </div>
    <div style="margin-top: 70px; margin-bottom: 30px;">
    <%= yield %>
    </div>
  </body>
</html>